name: Selenium Scraper

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          wget https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.4/browsermob-proxy-2.1.4-bin.zip
          unzip browsermob-proxy-2.1.4-bin.zip
          mv browsermob-proxy-2.1.4 /home/runner/browsermob-proxy
          python -m pip install selenium browsermob-proxy

      - name: Debug Information
        run: |
          echo "Running as $(whoami)"
          echo "Python version: $(python --version)"
          echo "Chrome version: $(google-chrome-stable --version)"
          echo "ChromeDriver version: $(chromedriver --version)"
          ls -l /usr/local/bin
          ls -l /home/runner/
          curl --version

      - name: Run Selenium Script
        run: python scripts/script.py

      - name: Upload Result (JSON Output)
        uses: actions/upload-artifact@v3
        with:
          name: soccer-links-json
          path: scripts/soccer_links.json
